"""Fixture loader — SDK load-only stub (generated by build_data.py).

The full upstream loader (libs/pipeline_engine/dsl/fixtures/loader.py) also
carries the regen writers and test-corpus plumbing; the SDK engine only ever
calls the four `load_*` functions below. The tables are the generated
artifacts A2/A3/A6 (dsl-type-system spec 02 §4.1) plus the tombstoned-options
table (dsl-mtf-clocks spec 02 §2.3), vendored beside this file by
scripts/build_data.py — regenerate the bundle, never hand-edit.
"""

import json
from pathlib import Path


FIXTURES_DIR = Path(__file__).parent


def _load(name: str) -> dict:
    with open(FIXTURES_DIR / name) as f:
        return json.load(f)


def load_domain_tables() -> dict:
    """Load the vendored generated domain tables (A2)."""
    return _load("domain_tables.json")


def load_validation_tables() -> dict:
    """Load the vendored generated validation tables (A6)."""
    return _load("validation_tables.json")


def load_judgment_tables() -> dict:
    """Load the vendored generated judgment tables (A3)."""
    return _load("judgment_tables.json")


def load_tombstoned_options() -> dict:
    """Load the vendored generated tombstoned-options table.

    The firing surface for ``TOMBSTONED_OPTION_PINNED`` (dsl-mtf-clocks spec 02
    §2.3). Upstream this table lives inside registry_metadata.json, which the
    wheel does not ship; build_data.py projects it into its own JSON here, so
    the SDK validator fires on exactly the pins the platform validator does.
    Same loud-fail contract as the tables above — a missing artifact raises
    rather than degrading to an empty table, which would leave the rule shipped
    with no firing surface at all.
    """
    return _load("tombstoned_options.json")
