"""Component registry operations using bundled JSON data.

Provides search, lookup, and type graph queries without importing
the components package. Uses registry.json and type_graph.json
generated by the build script.
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources
from typing import Any

from pipeline_engine.component_ranking import (  # noqa: F401  (re-exported)
    deprecation_fields,
    rank_components,
    score_component,
    tokenize_name,
    tokenize_text,
    visible,
)


@lru_cache(maxsize=1)
def _load_json(name: str) -> Any:
    """Load a bundled JSON file from keel.data."""
    ref = resources.files("keel.data").joinpath(name)
    return json.loads(ref.read_text())


def load_registry() -> dict:
    """Load registry.json and populate the ComponentRegistry.

    Returns the registry data dict. Also calls load_registry_from_json()
    to populate pipeline_engine's COMPONENT_REGISTRY for the validator.

    Defensive: in environments where `pipeline_engine` resolves to the
    full upstream `pipeline_engine` (e.g. anyone with `PYTHONPATH=libs`
    set via direnv inside the Keel monorepo) but pandas/numpy aren't
    installed, importing `pipeline_engine.base.registry` triggers a
    chain that loads `pipeline_engine.context` which needs pandas. We
    catch that ImportError so search/detail/etc. (which only need the
    JSON data) keep working. Validator-dependent paths (compose,
    validate, explain) will still surface a clean error when they
    actually need the registry.
    """
    data = _load_json("registry.json")

    try:
        from pipeline_engine.base.registry import COMPONENT_REGISTRY, load_registry_from_json
    except ImportError:
        # Heavy deps missing in this env. Bundled JSON data is still
        # usable for read-only queries (search, detail, after/before,
        # dump) — those operate on `data` directly.
        return data

    if not COMPONENT_REGISTRY:
        load_registry_from_json(data)

    return data


def _ensure_loaded() -> dict:
    """Ensure registry is loaded, return data."""
    return load_registry()


#: The K15 direction words. `keep` is the absence of a clock transfer.
CLOCK_DIRECTIONS: tuple[str, ...] = ("keep", "synth", "resample", "project")

#: Formal transfer op (spec 01 §5.1) → the direction word agents search by.
_CLOCK_OP_TO_DIRECTION: dict[str, str] = {
    "synth": "synth",
    "coarsen": "resample",
    "project": "project",
}


def clock_direction_for_op(op: str | None) -> str:
    """Map a `clock_transfer["op"]` to its `clock_direction` word.

    THE derivation. `scripts/build_data.py` calls this at regen to emit the
    `clock_direction` key into registry.json, and the runtime filter reads
    the same function, so the two can never disagree. An unknown op is a
    registration bug, not something to paper over — it raises.
    """
    if op is None:
        return "keep"
    try:
        return _CLOCK_OP_TO_DIRECTION[op]
    except KeyError:
        raise ValueError(
            f"Unknown clock_transfer op {op!r}. Known ops: "
            f"{sorted(_CLOCK_OP_TO_DIRECTION)}. A new op must be given a "
            f"clock_direction word here and the registry regenerated "
            f"(PYTHONPATH=libs python packages/keel-trade/keel-sdk/scripts/build_data.py)."
        ) from None


def clock_transfer_of(comp: dict[str, Any]) -> dict | None:
    """The declared `clock_transfer` of one component record, from either source.

    The bundled `registry.json` carries it top-level (`build_data.py`);
    keel-api's `GET /v1/components[/{name}]` serves it only per version
    (`versions[<n>].clock_transfer`, Q-2205), so the API record's own
    version — `latest`, else `version` — is read there (Q-2270: reading the
    top-level key alone made every hosted component read as `keep`, and the
    hosted results carried no `clock_direction` or `clock` block).
    """
    if "clock_transfer" in comp:
        transfer = comp.get("clock_transfer")
        return transfer if isinstance(transfer, dict) and transfer else None
    versions = comp.get("versions")
    version = comp.get("latest") if comp.get("latest") is not None else comp.get("version")
    if isinstance(versions, dict) and version is not None:
        entry = versions.get(str(version))
        if isinstance(entry, dict):
            transfer = entry.get("clock_transfer")
            return transfer if isinstance(transfer, dict) and transfer else None
    return None


def clock_direction_of(comp: dict[str, Any]) -> str:
    """The `clock_direction` of one registry record (bundled or keel-api).

    Derived from `clock_transfer` rather than read from the emitted
    `clock_direction` key so a stale bundled registry can never change
    filter behaviour; the freshness test asserts the two agree.
    """
    return clock_direction_for_op((clock_transfer_of(comp) or {}).get("op"))


# ─────────────────────────────────────────────────────────────────────────
# Component-search ranking — THE one scorer
# (dsl-multi-timeframe-clocks spec 02 §9.2)
#
# The implementation lives in `pipeline_engine.component_ranking`, imported
# above and re-exported here for every existing caller. THREE surfaces
# score with it — `search_components` below, the after/before overlay in
# `keel.tools.outcomes.components_search`, and `pipeline_engine.mcp.tools`'
# `strategy_components_search` (the chat-api / MCP path AI authors call).
# Two copies of a ranking rule is two rankings, which is the bug §9 exists
# to close; the R-25 audit found it again one layer out — MCP ranked by
# FAISS distance alone and still put `SignalResampler` above
# `TargetSignalResampler`, K15's exact inverse. `build_data.py` vendors the
# module into the wheel's `pipeline_engine` subset, so the shipped SDK and
# the monorepo execute the same bytes.
# ─────────────────────────────────────────────────────────────────────────
def keyword_matches(components: list[dict[str, Any]], keyword: str) -> list[dict[str, Any]]:
    """The components ``keyword`` names: its text inside the NAME, or a word
    of the DESCRIPTION that starts with it — name matches first.

    A bare substring over descriptions matched inside words (Q-2273 L6):
    ``ROC`` hit "process" and "procedure" in 49 components, so a
    ``keyword`` + ``query`` search led with components that never mention
    ROC and the keyword read as ignored. Case-insensitive.
    """
    import re

    kw = keyword.strip().lower()
    if not kw:
        return list(components)
    word_start = re.compile(r"(?<![a-z0-9])" + re.escape(kw))
    name_matches = [c for c in components if kw in (c.get("name") or "").lower()]
    named = {id(c) for c in name_matches}
    desc_matches = [
        c
        for c in components
        if id(c) not in named and word_start.search((c.get("description") or "").lower())
    ]
    return name_matches + desc_matches


def search_components(
    *,
    keyword: str | None = None,
    category: str | None = None,
    sub_category: str | None = None,
    input_type: str | None = None,
    output_type: str | None = None,
    clock_direction: str | None = None,
    query: str | None = None,
    top_k: int = 10,
    component_lock: dict[str, int] | None = None,
    include_deprecated: bool = False,
) -> list[dict[str, Any]]:
    """Search components using bundled registry data.

    A component whose latest version is deprecated is hidden unless
    ``include_deprecated`` (position-layer spec 04-R28, the ONE shared
    predicate ``component_ranking.visible``); a shown one carries ``status``
    and ``replacement_text``. Lookups by name never filter.

    Supports keyword filtering, category filtering, type filtering, and
    `clock_direction` filtering (`keep` / `synth` / `resample` / `project`).
    Results are scored by relevance and ordered by the §9.2 chain when
    `query` is provided.
    """
    data = _ensure_loaded()
    results = [c for c in data["components"] if visible(c, include_deprecated)]

    # Apply filters
    if category:
        cat_lower = category.lower()
        results = [c for c in results if c.get("category", "").lower() == cat_lower]

    if sub_category:
        sc_lower = sub_category.lower()
        results = [c for c in results if (c.get("sub_category") or "").lower() == sc_lower]

    if input_type:
        results = [c for c in results if c.get("input_type") == input_type]

    if output_type:
        results = [c for c in results if c.get("output_type") == output_type]

    if clock_direction:
        if clock_direction not in CLOCK_DIRECTIONS:
            raise ValueError(
                f"Unknown clock_direction {clock_direction!r}. "
                f"Expected one of {list(CLOCK_DIRECTIONS)}."
            )
        results = [c for c in results if clock_direction_of(c) == clock_direction]

    if keyword:
        results = keyword_matches(results, keyword)

    # Score + order by query if provided
    if query:
        results = rank_components(results, query)

    # Apply version lock
    if component_lock:
        locked_results = []
        for comp in results:
            name = comp["name"]
            if name in component_lock:
                ver = str(component_lock[name])
                versions = comp.get("versions", {})
                if ver in versions:
                    locked = dict(comp)
                    ver_data = versions[ver]
                    locked["parameters"] = ver_data.get("parameters", comp["parameters"])
                    locked["input_type"] = ver_data.get("input_type", comp["input_type"])
                    locked["output_type"] = ver_data.get("output_type", comp["output_type"])
                    locked_results.append(locked)
                else:
                    locked_results.append(comp)
            else:
                locked_results.append(comp)
        results = locked_results

    # Format output (compact view for search)
    output = []
    for comp in results[:top_k]:
        entry = {
            "name": comp["name"],
            "category": comp["category"],
            "description": (comp.get("description") or "").strip().split("\n\n")[0].strip()[:200],
            "input_type": comp.get("input_type", "Any"),
            "output_type": comp.get("output_type", "Any"),
        }
        if comp.get("sub_category"):
            entry["sub_category"] = comp["sub_category"]
        entry.update(position_search_fields(comp))
        entry.update(deprecation_fields(comp))
        # A distinguishing field, only where it distinguishes: the 10
        # clock-changing components carry it, the other ~174 `keep` ones
        # would just be noise in every result set.
        direction = clock_direction_of(comp)
        if direction != "keep":
            entry["clock_direction"] = direction
        output.append(entry)

    return output


def position_search_fields(comp: dict[str, Any]) -> dict[str, Any]:
    """What a search result says a position component is (spec 03-R64).

    ``position_role`` when the component declares one (``reader``,
    ``action``, ``factory`` …) and ``trade_safe: true`` when its latest
    version is certified to run on a trade window — keep-by-omission, so an
    ordinary component's entry is unchanged. The ONE projection both search
    paths (this bundled helper and the outcome tool's ``after``/``before``
    path) use.
    """
    out: dict[str, Any] = {}
    binding = comp.get("binding")
    if isinstance(binding, dict) and binding.get("role"):
        out["position_role"] = binding["role"]
    if comp.get("trade_safe") is not None:
        out["trade_safe"] = True
    return out


def get_component_detail(name: str, component_lock: dict[str, int] | None = None) -> dict[str, Any]:
    """Get full specification for a single component."""
    data = _ensure_loaded()

    for comp in data["components"]:
        if comp["name"] == name:
            result = dict(comp)
            # Apply version lock
            if component_lock and name in component_lock:
                ver = str(component_lock[name])
                versions = result.get("versions", {})
                if ver in versions:
                    ver_data = versions[ver]
                    result["parameters"] = ver_data.get("parameters", result["parameters"])
                    result["input_type"] = ver_data.get("input_type", result["input_type"])
                    result["output_type"] = ver_data.get("output_type", result["output_type"])
            return result

    raise KeyError(f"Component '{name}' not found in registry")


def get_components_after(name: str) -> list[dict[str, Any]]:
    """Find components that can DIRECTLY follow the given component.

    Reads the baked answer in ``type_graph.json`` — the live engine's
    ``is_compatible()`` verdict, precomputed by ``scripts/build_data.py``
    at regen (Q-0732). No string-matching or ``type_transitions``
    expansion here: this must return the same set as
    ``pipeline_engine.mcp.tools.strategy_components_after``.
    """
    data = _ensure_loaded()
    type_graph = _load_json("type_graph.json")

    # Find the component's output type
    comp = None
    for c in data["components"]:
        if c["name"] == name:
            comp = c
            break
    if comp is None:
        raise KeyError(f"Component '{name}' not found")

    output_type = comp["output_type"]
    # Position layer (spec 03-R65): a role-narrowed answer, baked per
    # component, wins over the base-type one.
    by_component = type_graph.get("successors_by_component", {})
    accepting_names = set(
        by_component[name]
        if name in by_component
        else type_graph["successors_by_output_type"][output_type]
    )

    results = []
    for c in data["components"]:
        if c["name"] in accepting_names and c["name"] != name:
            results.append(
                {
                    "name": c["name"],
                    "category": c["category"],
                    "description": (c.get("description") or "")
                    .strip()
                    .split("\n\n")[0]
                    .strip()[:200],
                    "input_type": c.get("input_type", "Any"),
                    "output_type": c.get("output_type", "Any"),
                }
            )
    return results


def get_components_before(name: str) -> list[dict[str, Any]]:
    """Find components that can DIRECTLY precede the given component.

    Reads the baked live-engine answer in ``type_graph.json`` (see
    ``get_components_after`` / Q-0732).
    """
    data = _ensure_loaded()
    type_graph = _load_json("type_graph.json")

    comp = None
    for c in data["components"]:
        if c["name"] == name:
            comp = c
            break
    if comp is None:
        raise KeyError(f"Component '{name}' not found")

    input_type = comp["input_type"]
    by_component = type_graph.get("predecessors_by_component", {})
    outputting_names = set(
        by_component[name]
        if name in by_component
        else type_graph["predecessors_by_input_type"][input_type]
    )

    results = []
    for c in data["components"]:
        if c["name"] in outputting_names and c["name"] != name:
            results.append(
                {
                    "name": c["name"],
                    "category": c["category"],
                    "description": (c.get("description") or "")
                    .strip()
                    .split("\n\n")[0]
                    .strip()[:200],
                    "input_type": c.get("input_type", "Any"),
                    "output_type": c.get("output_type", "Any"),
                }
            )
    return results


def get_components_dump() -> list[dict[str, Any]]:
    """Bulk dump of all components with full parameter details."""
    data = _ensure_loaded()
    return data["components"]
