"""Component registry operations using bundled JSON data.

Provides search, lookup, and type graph queries without importing
the components package. Uses registry.json and type_graph.json
generated by the build script.
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources
from typing import Any

from pipeline_engine.component_ranking import (  # noqa: F401  (re-exported)
    rank_components,
    score_component,
    tokenize_name,
    tokenize_text,
)


@lru_cache(maxsize=1)
def _load_json(name: str) -> Any:
    """Load a bundled JSON file from keel.data."""
    ref = resources.files("keel.data").joinpath(name)
    return json.loads(ref.read_text())


def load_registry() -> dict:
    """Load registry.json and populate the ComponentRegistry.

    Returns the registry data dict. Also calls load_registry_from_json()
    to populate pipeline_engine's COMPONENT_REGISTRY for the validator.

    Defensive: in environments where `pipeline_engine` resolves to the
    full upstream `pipeline_engine` (e.g. anyone with `PYTHONPATH=libs`
    set via direnv inside the Keel monorepo) but pandas/numpy aren't
    installed, importing `pipeline_engine.base.registry` triggers a
    chain that loads `pipeline_engine.context` which needs pandas. We
    catch that ImportError so search/detail/etc. (which only need the
    JSON data) keep working. Validator-dependent paths (compose,
    validate, explain) will still surface a clean error when they
    actually need the registry.
    """
    data = _load_json("registry.json")

    try:
        from pipeline_engine.base.registry import COMPONENT_REGISTRY, load_registry_from_json
    except ImportError:
        # Heavy deps missing in this env. Bundled JSON data is still
        # usable for read-only queries (search, detail, after/before,
        # dump) — those operate on `data` directly.
        return data

    if not COMPONENT_REGISTRY:
        load_registry_from_json(data)

    return data


def _ensure_loaded() -> dict:
    """Ensure registry is loaded, return data."""
    return load_registry()


#: The K15 direction words. `keep` is the absence of a clock transfer.
CLOCK_DIRECTIONS: tuple[str, ...] = ("keep", "synth", "resample", "project")

#: Formal transfer op (spec 01 §5.1) → the direction word agents search by.
_CLOCK_OP_TO_DIRECTION: dict[str, str] = {
    "synth": "synth",
    "coarsen": "resample",
    "project": "project",
}


def clock_direction_for_op(op: str | None) -> str:
    """Map a `clock_transfer["op"]` to its `clock_direction` word.

    THE derivation. `scripts/build_data.py` calls this at regen to emit the
    `clock_direction` key into registry.json, and the runtime filter reads
    the same function, so the two can never disagree. An unknown op is a
    registration bug, not something to paper over — it raises.
    """
    if op is None:
        return "keep"
    try:
        return _CLOCK_OP_TO_DIRECTION[op]
    except KeyError:
        raise ValueError(
            f"Unknown clock_transfer op {op!r}. Known ops: "
            f"{sorted(_CLOCK_OP_TO_DIRECTION)}. A new op must be given a "
            f"clock_direction word here and the registry regenerated "
            f"(PYTHONPATH=libs python packages/keel-trade/keel-sdk/scripts/build_data.py)."
        ) from None


def clock_direction_of(comp: dict[str, Any]) -> str:
    """The `clock_direction` of one registry record.

    Derived from `clock_transfer` rather than read from the emitted
    `clock_direction` key so a stale bundled registry can never change
    filter behaviour; the freshness test asserts the two agree.
    """
    return clock_direction_for_op((comp.get("clock_transfer") or {}).get("op"))


# ─────────────────────────────────────────────────────────────────────────
# Component-search ranking — THE one scorer
# (dsl-multi-timeframe-clocks spec 02 §9.2)
#
# The implementation lives in `pipeline_engine.component_ranking`, imported
# above and re-exported here for every existing caller. THREE surfaces
# score with it — `search_components` below, the after/before overlay in
# `keel.tools.outcomes.components_search`, and `pipeline_engine.mcp.tools`'
# `strategy_components_search` (the chat-api / MCP path AI authors call).
# Two copies of a ranking rule is two rankings, which is the bug §9 exists
# to close; the R-25 audit found it again one layer out — MCP ranked by
# FAISS distance alone and still put `SignalResampler` above
# `TargetSignalResampler`, K15's exact inverse. `build_data.py` vendors the
# module into the wheel's `pipeline_engine` subset, so the shipped SDK and
# the monorepo execute the same bytes.
# ─────────────────────────────────────────────────────────────────────────
def search_components(
    *,
    keyword: str | None = None,
    category: str | None = None,
    sub_category: str | None = None,
    input_type: str | None = None,
    output_type: str | None = None,
    clock_direction: str | None = None,
    query: str | None = None,
    top_k: int = 10,
    component_lock: dict[str, int] | None = None,
) -> list[dict[str, Any]]:
    """Search components using bundled registry data.

    Supports keyword filtering, category filtering, type filtering, and
    `clock_direction` filtering (`keep` / `synth` / `resample` / `project`).
    Results are scored by relevance and ordered by the §9.2 chain when
    `query` is provided.
    """
    data = _ensure_loaded()
    results = list(data["components"])

    # Apply filters
    if category:
        cat_lower = category.lower()
        results = [c for c in results if c.get("category", "").lower() == cat_lower]

    if sub_category:
        sc_lower = sub_category.lower()
        results = [c for c in results if (c.get("sub_category") or "").lower() == sc_lower]

    if input_type:
        results = [c for c in results if c.get("input_type") == input_type]

    if output_type:
        results = [c for c in results if c.get("output_type") == output_type]

    if clock_direction:
        if clock_direction not in CLOCK_DIRECTIONS:
            raise ValueError(
                f"Unknown clock_direction {clock_direction!r}. "
                f"Expected one of {list(CLOCK_DIRECTIONS)}."
            )
        results = [c for c in results if clock_direction_of(c) == clock_direction]

    if keyword:
        kw_lower = keyword.lower()
        name_matches = []
        desc_matches = []
        for c in results:
            if kw_lower in c.get("name", "").lower():
                name_matches.append(c)
            elif kw_lower in c.get("description", "").lower():
                desc_matches.append(c)
        results = name_matches + desc_matches

    # Score + order by query if provided
    if query:
        results = rank_components(results, query)

    # Apply version lock
    if component_lock:
        locked_results = []
        for comp in results:
            name = comp["name"]
            if name in component_lock:
                ver = str(component_lock[name])
                versions = comp.get("versions", {})
                if ver in versions:
                    locked = dict(comp)
                    ver_data = versions[ver]
                    locked["parameters"] = ver_data.get("parameters", comp["parameters"])
                    locked["input_type"] = ver_data.get("input_type", comp["input_type"])
                    locked["output_type"] = ver_data.get("output_type", comp["output_type"])
                    locked_results.append(locked)
                else:
                    locked_results.append(comp)
            else:
                locked_results.append(comp)
        results = locked_results

    # Format output (compact view for search)
    output = []
    for comp in results[:top_k]:
        entry = {
            "name": comp["name"],
            "category": comp["category"],
            "description": (comp.get("description") or "").strip().split("\n\n")[0].strip()[:200],
            "input_type": comp.get("input_type", "Any"),
            "output_type": comp.get("output_type", "Any"),
        }
        if comp.get("sub_category"):
            entry["sub_category"] = comp["sub_category"]
        # A distinguishing field, only where it distinguishes: the 10
        # clock-changing components carry it, the other ~174 `keep` ones
        # would just be noise in every result set.
        direction = clock_direction_of(comp)
        if direction != "keep":
            entry["clock_direction"] = direction
        output.append(entry)

    return output


def get_component_detail(name: str, component_lock: dict[str, int] | None = None) -> dict[str, Any]:
    """Get full specification for a single component."""
    data = _ensure_loaded()

    for comp in data["components"]:
        if comp["name"] == name:
            result = dict(comp)
            # Apply version lock
            if component_lock and name in component_lock:
                ver = str(component_lock[name])
                versions = result.get("versions", {})
                if ver in versions:
                    ver_data = versions[ver]
                    result["parameters"] = ver_data.get("parameters", result["parameters"])
                    result["input_type"] = ver_data.get("input_type", result["input_type"])
                    result["output_type"] = ver_data.get("output_type", result["output_type"])
            return result

    raise KeyError(f"Component '{name}' not found in registry")


def get_components_after(name: str) -> list[dict[str, Any]]:
    """Find components that can follow the given component (by output type)."""
    data = _ensure_loaded()
    type_graph = _load_json("type_graph.json")

    # Find the component's output type
    comp = None
    for c in data["components"]:
        if c["name"] == name:
            comp = c
            break
    if comp is None:
        raise KeyError(f"Component '{name}' not found")

    output_type = comp["output_type"]

    # Find all components that accept this output type
    accepting_names = set(type_graph.get("input_type_to_names", {}).get(output_type, []))

    # Also check type transitions for compatible types
    transitions = data.get("type_transitions", {})
    if output_type in transitions:
        for _cat, out_types in transitions[output_type].items():
            for ot in out_types:
                accepting_names.update(type_graph.get("input_type_to_names", {}).get(ot, []))

    results = []
    for c in data["components"]:
        if c["name"] in accepting_names and c["name"] != name:
            results.append(
                {
                    "name": c["name"],
                    "category": c["category"],
                    "description": (c.get("description") or "")
                    .strip()
                    .split("\n\n")[0]
                    .strip()[:200],
                    "input_type": c.get("input_type", "Any"),
                    "output_type": c.get("output_type", "Any"),
                }
            )
    return results


def get_components_before(name: str) -> list[dict[str, Any]]:
    """Find components that can precede the given component (by input type)."""
    data = _ensure_loaded()
    type_graph = _load_json("type_graph.json")

    comp = None
    for c in data["components"]:
        if c["name"] == name:
            comp = c
            break
    if comp is None:
        raise KeyError(f"Component '{name}' not found")

    input_type = comp["input_type"]

    outputting_names = set(type_graph.get("output_type_to_names", {}).get(input_type, []))

    results = []
    for c in data["components"]:
        if c["name"] in outputting_names and c["name"] != name:
            results.append(
                {
                    "name": c["name"],
                    "category": c["category"],
                    "description": (c.get("description") or "")
                    .strip()
                    .split("\n\n")[0]
                    .strip()[:200],
                    "input_type": c.get("input_type", "Any"),
                    "output_type": c.get("output_type", "Any"),
                }
            )
    return results


def get_components_dump() -> list[dict[str, Any]]:
    """Bulk dump of all components with full parameter details."""
    data = _ensure_loaded()
    return data["components"]
