"""`keel project init` — write multi-IDE project templates.

Per spec §10 (lines 1353-1397). Detects the active IDE via the same
env-var set `keel.cli.agent_mode` uses, then writes the canonical
project files. All four IDE files share the same content shape; each
just respects its own location convention.

Files written:
  - CLAUDE.md         (Claude Code; also the universal agent guide)
  - AGENTS.md         (generic, the emerging cross-IDE convention)
  - .cursorrules      (Cursor)
  - .windsurf/rules.md (Windsurf)
  - .keel/workspace.yaml (local Keel workspace pointer)
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from keel.cli.agent_mode import detected_agent


@dataclass
class WrittenFile:
    path: Path
    existed_before: bool
    skipped: bool = False


_TEMPLATE = """\
# Project: {project_name}

## What Keel is (2 sentences)
Keel is a quantitative trading platform: strategy DSL → backtest → live deploy on Hyperliquid.
This project uses the Keel CLI + MCP (`keel-trade`) to author, backtest, and deploy strategies.

## Active strategy / dataset
- Strategy: {strategy_pointer}
- Cache: $KEEL_CACHE_PATH (set this env var to point at your local parquet cache)
- Latest backtest: (auto-updated by post-backtest hook)

## Recommended workflow
1. Ask: "what should I look at first?" — agent loads context from `keel://context/project`
2. Search components: `keel components search <thing>` or `keel_components_search(keyword=<thing>)`
3. Compose + validate: `keel strategy compose --source-file <file> --dry-run`
4. Backtest: `keel backtest run <strategy_id> --start-date <YYYY-MM-DD> [--end-date <YYYY-MM-DD>]`
5. Inspect: open the authenticated URL printed at the end (e.g. `app.usekeel.io/backtests/<id>`)
6. Iterate: edit, push back via `keel strategy compose --strategy-id <id> --source-file ...`

## Where to find help
- DSL reference: read MCP resource `keel://dsl/reference/<topic>` or run `keel help <topic>`
- Component catalog: read MCP resource `keel://components/catalog` or `keel components search`
- Bundled skills (workflow scaffolding): `keel skills list` — 8 skills cover the full lifecycle
- Stuck? Run `keel doctor`

## Conventions
- Authenticated `app.usekeel.io/...` URLs are private. Public `usekeel.io/share/...` URLs
  are explicit-only — generated by `keel share create <target_id>` when the user asks.
- Live trading is double-locked: OAuth `live` scope (server) + local arming (`keel arm live`).
"""


_WORKSPACE_YAML = """\
# Keel workspace metadata — auto-written by `keel project init`.
# Edit `linked_strategy_id` once you've created a strategy on the platform.
name: {project_name}
linked_strategy_id: {strategy_pointer}
"""


_CLAUDE_HOOKS_CONFIG = """\
# Claude Code hooks (.claude/settings.json hook block)
# Drop into .claude/settings.json's `hooks` array if you want
# automatic pre-/post- Keel tool integrations.
{
  "hooks": [
    {
      "matcher": {"tool_name": "keel_backtest_run"},
      "lifecycle": "pre_tool_use",
      "command": "keel strategy compose --source-file ${file} --dry-run",
      "rationale": "Local validation in <1s before paying for a real backtest."
    },
    {
      "matcher": {"tool_name": "keel_live_deploy"},
      "lifecycle": "pre_tool_use",
      "command": "keel live deploy --preview ${strategy_id} --account-id ${account_id}",
      "rationale": "Print the preview to the visible chat stream so the user sees what's about to fire."
    },
    {
      "matcher": {"tool_name": "keel_backtest_run"},
      "lifecycle": "post_tool_use",
      "command": "keel backtest summarize ${backtest_id} --format json",
      "rationale": "Surface metrics + share URL in the chat stream."
    }
  ]
}
"""


def render_template(
    project_name: str,
    strategy_pointer: str = "(none yet — create one with `keel strategy compose`)",
) -> str:
    return _TEMPLATE.format(project_name=project_name, strategy_pointer=strategy_pointer)


def render_workspace_yaml(project_name: str, strategy_pointer: str = "null") -> str:
    return _WORKSPACE_YAML.format(project_name=project_name, strategy_pointer=strategy_pointer)


def claude_hooks_config() -> str:
    return _CLAUDE_HOOKS_CONFIG


def detect_ide() -> str | None:
    """Return a short label for the active IDE if detectable, else None."""
    agent = detected_agent()
    if agent:
        return agent
    return None


def init_project(cwd: Path | None = None, *, force: bool = False) -> list[WrittenFile]:
    """Write the four IDE files + .keel/workspace.yaml.

    `force=True` overwrites existing files; otherwise existing files are
    skipped and reported in the returned `WrittenFile.skipped` flag.
    """
    cwd = cwd or Path.cwd()
    project_name = cwd.name
    body = render_template(project_name=project_name)

    targets: Iterable[tuple[Path, str]] = (
        (cwd / "CLAUDE.md", body),
        (cwd / "AGENTS.md", body),
        (cwd / ".cursorrules", body),
        (cwd / ".windsurf" / "rules.md", body),
        (cwd / ".keel" / "workspace.yaml", render_workspace_yaml(project_name)),
    )

    written: list[WrittenFile] = []
    for path, content in targets:
        existed = path.exists()
        if existed and not force:
            written.append(WrittenFile(path=path, existed_before=True, skipped=True))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(WrittenFile(path=path, existed_before=existed, skipped=False))
    return written
