"""Q-2242 — a parameter's hard limit and typical range reach an agent as two
separately labelled things, in the JSON detail AND the markdown table.

`min` / `max` are the HARD limits (absent = unbounded, `min_exclusive` /
`max_exclusive` make a bound strict); `typical: [lo, hi]` is guidance only.
Every fixture here is a SYNTHETIC constraints dict — the bundled
registry.json is regenerated by the integration lane after the component
data lands, so these tests must not depend on what it holds today.

SEEDS (run 2026-10-01, each reverted by reversing the edit):
  A. `format_interval` ignores `lo_exclusive` (always `[`) —
     `test_interval_notation[exclusive-floor-unbounded-above]`,
     `test_markdown_glyph_is_infinity`, `test_json_detail_labels_both_ranges` and
     `test_markdown_table_has_separate_labelled_columns` red (4 of 15); the
     inclusive / legacy / emission arms stay green.
  B. `_param_extra` keeps `typical` in the trailing constraints blob —
     `test_markdown_table_has_separate_labelled_columns` reds on the
     "typical only in its own column" assertion (1 of 15); the JSON arms
     stay green.
  C. build_data's `_param_constraints_field` projects to `{min, max, step,
     options}` — `test_build_data_emits_constraints_verbatim` and the
     hydrator round-trip red (2 of 15); every rendering arm stays green.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
from types import SimpleNamespace

import pytest
from keel.tools.outcomes._param_range import (
    RANGE_NOTE,
    format_interval,
    hard_limit,
    param_range,
    typical_range,
)
from keel.tools.outcomes._reading_markdown import render_component
from keel.tools.outcomes.components_help import _shape_detail


#: The canonical case from the brief: TakeProfitExit.profit_threshold after
#: Q-2242 — hard (0, ∞), typical [0.01, 1].
TP = {"min": 0, "min_exclusive": True, "typical": [0.01, 1.0], "step": 0.01}


@pytest.mark.parametrize(
    "constraints,hard,typical",
    [
        pytest.param(TP, "(0, inf)", "[0.01, 1]", id="exclusive-floor-unbounded-above"),
        pytest.param({"min": 1, "typical": [5, 252]}, "[1, inf)", "[5, 252]", id="inclusive-floor"),
        pytest.param(
            {"max": 0.5, "max_exclusive": True, "typical": [0.1, 0.4]},
            "(-inf, 0.5)",
            "[0.1, 0.4]",
            id="exclusive-ceiling-unbounded-below",
        ),
        pytest.param({"typical": [1e-12, 1e-4]}, "(-inf, inf)", "[1e-12, 0.0001]", id="no-bound"),
        pytest.param({"min": 2, "max": 100}, "[2, 100]", None, id="legacy-no-typical"),
        pytest.param({"options": ["a", "b"]}, None, None, id="enum-only"),
        pytest.param({}, None, None, id="empty"),
        # An exclusive flag with its bound absent is meaningless — never a bracket.
        pytest.param(
            {"min_exclusive": True, "typical": [1, 2]}, "(-inf, inf)", "[1, 2]", id="stray-flag"
        ),
    ],
)
def test_interval_notation(constraints, hard, typical) -> None:
    assert hard_limit(constraints) == hard
    assert typical_range(constraints) == typical
    expected = (
        None
        if hard is None
        else {"hard_limit": hard, **({"typical_guidance": typical} if typical else {})}
    )
    assert param_range(constraints) == expected


def test_markdown_glyph_is_infinity() -> None:
    assert hard_limit(TP, inf="∞") == "(0, ∞)"
    assert format_interval(1, False, None, False, inf="∞") == "[1, ∞)"


def _detail(constraints: dict) -> dict:
    return {
        "name": "TakeProfitExit",
        "category": "signal_transform",
        "input_type": "SignalSeries",
        "output_type": "BinarySignal",
        "description": "Synthetic.",
        "parameters": [
            {
                "name": "entry_slot",
                "type": "str",
                "default": None,
                "required": True,
                "description": "slot",
                "constraints": {},
            },
            {
                "name": "profit_threshold",
                "type": "float",
                "default": 0.1,
                "required": False,
                "description": "Gain that fires the exit.",
                "constraints": constraints,
            },
        ],
    }


def test_json_detail_labels_both_ranges() -> None:
    detail = _detail(dict(TP))
    shaped = _shape_detail(detail)
    by_name = {p["name"]: p for p in shaped["parameters"]}
    assert by_name["profit_threshold"]["range"] == {
        "hard_limit": "(0, inf)",
        "typical_guidance": "[0.01, 1]",
    }
    # Additive: the raw keys still reach the reader verbatim.
    assert by_name["profit_threshold"]["constraints"] == TP
    assert "range" not in by_name["entry_slot"]
    assert shaped["range_note"] == RANGE_NOTE
    # The registry record is never mutated (it is the module-level cache).
    assert "range" not in detail["parameters"][1]


def test_no_range_note_when_no_param_has_a_range() -> None:
    """CONTROL: a component with no ranged param carries no note."""
    shaped = _shape_detail(_detail({"options": ["close", "open"]}))
    assert "range_note" not in shaped
    assert all("range" not in p for p in shaped["parameters"])


def test_markdown_table_has_separate_labelled_columns() -> None:
    text = render_component(_shape_detail(_detail(dict(TP))))
    header = next(line for line in text.splitlines() if line.startswith("| parameter"))
    cols = [c.strip() for c in header.strip("|").split("|")]
    assert cols == [
        "parameter",
        "type",
        "default",
        "required",
        "hard limit",
        "typical (guidance)",
        "description",
        "constraints",
    ]
    row = next(line for line in text.splitlines() if line.startswith("| `profit_threshold`"))
    cells = [c.strip() for c in row.strip("|").split("|")]
    assert cells[cols.index("hard limit")] == "(0, ∞)"
    assert cells[cols.index("typical (guidance)")] == "[0.01, 1]"
    # typical lives ONLY in its own column: the trailing blob keeps step, and
    # neither the range keys nor the derived `range` repeat there.
    blob = json.loads(cells[cols.index("constraints")])
    assert blob["constraints"] == {"step": 0.01}
    assert "range" not in blob
    # The legend says what the columns mean, before the table.
    assert "hard limit = the only range the validator rejects" in text
    assert text.index("hard limit = ") < text.index("| parameter")
    # The note is rendered as prose, not dumped as a trailing details line.
    assert "range_note" not in text


def test_markdown_legacy_registry_shows_hard_only() -> None:
    """A registry that predates `typical` renders its [min, max] as the hard
    limit and an EMPTY typical cell — a typical range is never invented."""
    text = render_component(_shape_detail(_detail({"min": 0.01, "max": 1.0, "step": 0.01})))
    row = next(line for line in text.splitlines() if line.startswith("| `profit_threshold`"))
    cells = [c.strip() for c in row.strip("|").split("|")]
    assert cells[4] == "[0.01, 1]"
    assert cells[5] == ""


# ─── build_data.py emission ────────────────────────────────────────────────

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "build_data.py"


@pytest.fixture(scope="module")
def build_data():
    spec = importlib.util.spec_from_file_location("_build_data_param_range", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_build_data_emits_constraints_verbatim(build_data) -> None:
    declared = {
        "min": 0,
        "min_exclusive": True,
        "max": 10,
        "max_exclusive": True,
        "typical": [0.01, 1.0],
        "step": 0.01,
    }
    emitted = build_data._param_constraints_field(SimpleNamespace(constraints=declared))
    assert emitted == declared
    assert emitted is not declared and emitted["typical"] is not declared["typical"]
    # An unbounded param emits no bound key at all — absence IS the encoding.
    unbounded = build_data._param_constraints_field(
        SimpleNamespace(constraints={"typical": [1, 2]})
    )
    assert unbounded == {"typical": [1, 2]}
    assert build_data._param_constraints_field(SimpleNamespace(constraints=None)) == {}


def test_emitted_constraints_survive_the_sdk_hydrator(build_data) -> None:
    """What build_data writes, the SDK's vendored hydrator reads back intact —
    so the vendored validator sees the exclusive flag and the absent bound."""
    from pipeline_engine.base.registry_types import _param_from_json

    emitted = build_data._param_constraints_field(SimpleNamespace(constraints=dict(TP)))
    info = _param_from_json(
        {
            "name": "profit_threshold",
            "type": "float",
            "default": 0.1,
            "required": False,
            "constraints": json.loads(json.dumps(emitted)),
            "type_structure": {"kind": "class", "name": "float"},
        },
        "TakeProfitExit",
        merge_top_level=True,
    )
    assert info.constraints == {
        "min": 0,
        "min_exclusive": True,
        "typical": [0.01, 1.0],
        "step": 0.01,
    }
    assert "max" not in info.constraints
