"""Every SDK save of a position-layer upgrade carries the planner's lock (Q-2448).

The census shape (L3a-fix): an EWMA-cross entry pinned at Crossover v1 plus a
trailing stop. The upgrade's TradeManager rule applies Crossover to a trade
value, which only Crossover v2 is certified for, so the planner moves the pin
(``lock_changes``) and the upgraded text is valid ONLY under its returned
``component_lock``. A save that sends the stored pins (compose) or none
(push) lets keel-api re-evolve them: Crossover stays v1 and the saved version
fails ``TRADE_OP_NOT_TRADE_SAFE``.

- ``keel_strategy_upgrade`` ``apply=true`` saves the planner's lock and the
  envelope reports ``lock_changes`` (the dry run too).
- ``keel_strategy_compose`` / ``keel_strategy_push`` RECOGNISE a text that is
  the planner's upgrade of HEAD (the issue's ``result_source``) and save it at
  the planner's lock; a hand edit is not recognised.
- Control: an upgrade that moves no pin saves byte-identically to before.

The real planner runs (no fake engine). It must be the CURRENT planner: the
wheel's vendored copy is regenerated by ``scripts/build_data.py``.
"""

from __future__ import annotations

from typing import Any
from unittest.mock import MagicMock, patch

import pytest
from keel.tools.outcomes import OUTCOMES, ToolContext, _bootstrap


@pytest.fixture(autouse=True)
def _bootstrap_outcomes():
    _bootstrap()
    from keel.tools.outcomes import (  # noqa: F401
        strategy_compose,
        strategy_push,
        strategy_upgrade,
    )


XOVER_TRAIL = """Globals(target_timeframe="1d")
Universe(symbols=["BTC"])
Execution(rebalance="on_change")

Pipeline([
    PriceDataLoader(),
    Store("ohlcv"),
    {"fast": [EWMA(window=10, min_periods=10)], "slow": [EWMA(window=30, min_periods=30)]},
    Crossover(),
    ThresholdCross(upper=0.0, lower=0.0),
    Store("entries"),
    {"trailing": [TrailingStopExit(entry_slot="entries", ohlcv_slot="ohlcv", atr_multiplier=2.0, atr_period=14)]},
    MaskOr(),
    Store("exits"),
    PositionStateMachine(entry_slot="entries", exit_slot="exits"),
    EqualWeightSizer(target_leverage=1.0),
])
"""

#: Control: a fixed stop's rule applies no Crossover, so no pin moves.
XOVER_STOP = XOVER_TRAIL.replace(
    'TrailingStopExit(entry_slot="entries", ohlcv_slot="ohlcv", atr_multiplier=2.0, atr_period=14)',
    'MaxDrawdownStopLoss(entry_slot="entries", ohlcv_slot="ohlcv", drawdown_threshold=0.05)',
)

LOCK_HASH = "b" * 64


def _census_lock(src: str) -> dict[str, int]:
    from keel.tools.local import _ensure_registry

    from pipeline_engine.base.lock import evolve_lock
    from pipeline_engine.dsl.parser import parse_strategy

    _ensure_registry()
    lock = evolve_lock({}, parse_strategy(src))
    lock["Crossover"] = 1
    return lock


def _planned(src: str) -> tuple[dict[str, int], dict[str, Any]]:
    from keel.tools.outcomes.strategy_upgrade import run_upgrade

    lock = _census_lock(src)
    return lock, run_upgrade(src, dict(lock), None)


@pytest.fixture(scope="module")
def census():
    lock, out = _planned(XOVER_TRAIL)
    # Non-vacuity: the stored lock pins v1, and the planner moves it.
    assert lock["Crossover"] == 1
    assert [c["component"] for c in out["lock_changes"]] == ["Crossover"]
    assert out["component_lock"]["Crossover"] == 2 and out["validation"]["ok"]
    return lock, out


@pytest.fixture(scope="module")
def control():
    lock, out = _planned(XOVER_STOP)
    assert out["lock_changes"] == [] and out["validation"]["ok"]
    assert out["component_lock"]["Crossover"] == 1
    return lock, out


class _Client:
    """Records calls; canned GET payloads by path, ``{}`` otherwise."""

    def __init__(self, get_payloads: dict[str, Any]) -> None:
        self.get_payloads = get_payloads
        self.calls: list[tuple[str, str, Any]] = []

    def get(self, path: str, **params: Any) -> Any:
        self.calls.append(("GET", path, params or None))
        return self.get_payloads.get(path, {})

    def patch(self, path: str, json: dict | None = None) -> Any:
        self.calls.append(("PATCH", path, json))
        return {"strategy_id": "str_1", "current_sequence": 5, "head_commit_id": "cmt_new"}

    def bodies(self, verb: str) -> list[dict]:
        return [body for v, _p, body in self.calls if v == verb]


def _head_client(src: str, lock: dict[str, int]) -> _Client:
    return _Client(
        {
            "/v1/strategies/str_1": {
                "strategy_id": "str_1",
                "component_lock": lock,
                "lock_hash": LOCK_HASH,
            },
            "/v1/strategies/str_1/versions/HEAD/source": {
                "source": src,
                "component_lock": lock,
                "commit_id": "cmt_old",
                "sequence_number": 4,
                "source_hash": "sha_old",
            },
        }
    )


def _ctx(client: Any) -> ToolContext:
    return ToolContext(api_client=client, is_tty=False, app_url="https://app.usekeel.io")


# ─── keel_strategy_upgrade ──────────────────────────────────────────────────


class TestUpgradeTool:
    def test_apply_saves_the_planners_lock_and_reports_the_move(self, census):
        lock, out = census
        client = _head_client(XOVER_TRAIL, lock)
        env = (
            OUTCOMES["keel_strategy_upgrade"]
            .handler({"strategy_id": "str_1", "apply": True}, _ctx(client))
            .to_envelope()
        )
        (body,) = client.bodies("PATCH")
        assert body["source"] == out["source"]
        assert body["component_lock"] == out["component_lock"]
        assert body["component_lock"]["Crossover"] == 2
        assert [c["component"] for c in env["lock_changes"]] == ["Crossover"]
        assert env["applied"] is True

    def test_the_dry_run_reports_the_move_and_writes_nothing(self, census):
        lock, _out = census
        client = _head_client(XOVER_TRAIL, lock)
        env = (
            OUTCOMES["keel_strategy_upgrade"]
            .handler({"strategy_id": "str_1"}, _ctx(client))
            .to_envelope()
        )
        assert client.bodies("PATCH") == []
        assert [(c["from"], c["to"]) for c in env["lock_changes"]] == [(1, 2)]
        assert env["component_lock"]["Crossover"] == 2

    def test_control_no_moved_pin_reports_none_and_keeps_the_pins(self, control):
        lock, out = control
        client = _head_client(XOVER_STOP, lock)
        env = (
            OUTCOMES["keel_strategy_upgrade"]
            .handler({"strategy_id": "str_1", "apply": True}, _ctx(client))
            .to_envelope()
        )
        (body,) = client.bodies("PATCH")
        # (.get: the control is about the save, and holds with or without the report)
        assert env.get("lock_changes", []) == []
        assert body["component_lock"] == out["component_lock"]
        assert body["component_lock"]["Crossover"] == 1


# ─── keel_strategy_compose (the listed profile's route) ────────────────────


def _compose(client: _Client, source: str, **extra: Any) -> dict:
    return (
        OUTCOMES["keel_strategy_compose"]
        .handler({"strategy_id": "str_1", "source": source, **extra}, _ctx(client))
        .to_envelope()
    )


class TestCompose:
    def test_saving_the_result_source_carries_the_planners_lock(self, census):
        lock, out = census
        client = _head_client(XOVER_TRAIL, lock)
        env = _compose(client, out["source"])
        (body,) = client.bodies("PATCH")
        assert body["component_lock"] == out["component_lock"]
        assert body["expected_lock_hash"] == LOCK_HASH  # still guarded on the read
        assert [c["component"] for c in env["lock_changes"]] == ["Crossover"]
        assert env["validation"]["ok"] is True, env["validation"]

    def test_the_dry_run_validates_at_the_planners_lock(self, census):
        lock, out = census
        client = _head_client(XOVER_TRAIL, lock)
        seen: list = []

        def compile_(source, component_lock=None):
            seen.append(component_lock)
            return {"compiled": True}

        with patch("keel.tools.remote.strategy_compile", compile_):
            env = _compose(client, out["source"], dry_run=True)
        assert seen and seen[0]["Crossover"] == 2  # the compile preview's lock too
        assert client.bodies("PATCH") == []
        codes = {e.get("code") for e in env["validation"]["errors"] if isinstance(e, dict)}
        assert "TRADE_OP_NOT_TRADE_SAFE" not in codes, env["validation"]
        assert [c["component"] for c in env["lock_changes"]] == ["Crossover"]

    def test_a_hand_edited_text_is_not_recognised(self, census):
        """Recognition, not inference: one changed parameter and the save
        keeps the stored pins (the server's validation then speaks)."""
        lock, out = census
        edited = out["source"].replace("window=10", "window=11")
        assert edited != out["source"]
        client = _head_client(XOVER_TRAIL, lock)
        env = _compose(client, edited)
        (body,) = client.bodies("PATCH")
        assert body["component_lock"] == lock
        assert "lock_changes" not in env

    def test_control_an_upgrade_moving_no_pin_saves_exactly_as_before(self, control):
        lock, out = control
        client = _head_client(XOVER_STOP, lock)
        env = _compose(client, out["source"])
        (body,) = client.bodies("PATCH")
        assert body["component_lock"] == lock  # the stored pins, as before
        assert "lock_changes" not in env


# ─── keel_strategy_push ─────────────────────────────────────────────────────


@pytest.fixture
def workspace_root(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    with patch("keel.workspace.WORKSPACE_ROOT", tmp_path / "ws"):
        yield tmp_path / "ws"


def _push(root, base: str, lock: dict[str, int], local: str) -> tuple[dict, dict]:
    from keel.workspace import STRATEGY_FILE, WorkspaceMeta, _compute_hash, push

    ws_dir = root / "str_1"
    ws_dir.mkdir(parents=True)
    (ws_dir / STRATEGY_FILE).write_text(local)
    WorkspaceMeta(
        strategy_id="str_1",
        name="census",
        source_hash=_compute_hash(base),
        checked_out_at="2026-10-05T00:00:00Z",
        current_sequence=4,
    ).save(ws_dir)
    inst = MagicMock()
    inst.get.return_value = {"source": base, "component_lock": lock}
    inst.patch.return_value = {"strategy_id": "str_1", "current_sequence": 5}
    with patch("keel.client.KeelClient", return_value=inst):
        result = push(strategy_id="str_1", message="upgrade")
    return inst.patch.call_args.kwargs["json"], result


class TestPush:
    def test_pushing_the_upgrade_sends_the_planners_lock(self, workspace_root, census):
        lock, out = census
        body, result = _push(workspace_root, XOVER_TRAIL, lock, out["source"])
        assert body["component_lock"] == out["component_lock"]
        assert body["component_lock"]["Crossover"] == 2
        assert [c["component"] for c in result["lock_changes"]] == ["Crossover"]

    def test_control_an_upgrade_moving_no_pin_pushes_exactly_as_before(
        self, workspace_root, control
    ):
        lock, out = control
        body, result = _push(workspace_root, XOVER_STOP, lock, out["source"])
        assert "component_lock" not in body  # keel-api evolves its pins, as before
        assert result.get("lock_changes", []) == []
