"""Keel MCP connector branding — the server icon.

The Keel mark (``scripts/icon.png``, the same asset the MCPB bundle ships)
is embedded here as a base64 ``data:`` URI so it travels inside the
pip/pipx wheel — ``scripts/`` is dev tooling and is NOT packaged, and a
committed PNG under ``keel/data`` would trip the repo artifact-gate. The
mark is passed as ``serverInfo.icons`` on the FastMCP construction; the
custom-connector UIs in Cursor and Claude Desktop surface it (claude.ai
custom connectors do not render ``serverInfo.icons`` yet, but the field is
correct and forward-compatible).

Regenerate after changing ``scripts/icon.png``:
    python -c "import base64,pathlib; \
      b=base64.b64encode(pathlib.Path('packages/keel-trade/keel-sdk/scripts/icon.png').read_bytes()).decode(); \
      print(len(b))"
and paste the new base64 below (keep sizes in sync with the PNG's real
dimensions).
"""

from __future__ import annotations


KEEL_ICON_MIME = "image/png"
# packages/keel-trade/keel-sdk/scripts/icon.png — 512×512 PNG.
KEEL_ICON_SIZES = ["512x512"]
KEEL_WEBSITE_URL = "https://usekeel.io"

KEEL_ICON_DATA_URI = (
    "data:image/png;base64,"
    "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAQAElEQVR4nOzdS24sR3aA4WC1NuEe9UheALdBzpt+wRBt2PNeRy/A"
    "sFto+D1vb0OAp9YC7KkXoKtqJlVFFcliMbMyMjPinO8DjHttNGAZV77xn1MRxa8KAJDOVwUASEcAAEBCAgAAEhIAAJCQAACAhAQA"
    "ACQkAAAgIQEAAAkJAABISAAAQEICAAASEgAAkJAAAICEBAAAJCQAACAhAQAACQkAAEhIAABAQgIAABISAACQkAAAgIQEAAAkJAAA"
    "ICEBAAAJ7QoQwje/3v/yb/5sf1sARhAAEIsAAEYRABCMLQAwhgCAeG6HjwMKwAUCAAK6ufFRAHCZAICAngLgT2wBgEsEAARlCwBc"
    "IgAgKFsA4BIBAIHtduWuAJwhACA4zwKBcwQAxOdZIPCOAIAEXAgE3hIAkIALgcBbAgCSsAUATgkASMIWADglACARWwDgSABAIsMW"
    "wLNAYCAAIB8BAAgAyOjxYX9fgNQEACTkQiAgACApFwIhNwEASdkCQG4CABKzBYC8BAAk5lkg5CUAAAEACQkAoNgCQD4CABjcuhAI"
    "uQgA4JkLgZCLAACeeRYIuQgA4IUtAOQhAIAXtgCQhwAAXtntyl0BwhMAwDueBUJ8AgA4x7NACE4AAGe5EAixCQDgLBcCITYBAHzI"
    "FgDiEgDAh2wBIC4BAFxkCwAxCQDgomEL4FkgxCMAgDEEAAQjAIBRHh/29wUIQwAAo7gQCLEIAGA0FwIhDgEAjGYLAHEIAGASWwCI"
    "QQAAk3gWCDEIAOAaAgA6JwCAq9gCQN8EAHCtWxcCoV8CALiaC4HQLwEAXM2zQOiXAABmsQWAPgkAYBZbAOiTAABm2+3KXQG6IgCA"
    "KjwLhL4IAKAWzwKhIwIAqMaFQOiHAACqcSEQ+iEAgKpsAaAPAgCoyhYA+iAAgOpsAaB9AgCobtgCeBYIbRMAwFIEADRMAACLeXzY"
    "3xegSQIAWIwLgdAuAQAsyoVAaJMAABZlCwBtEgDA4mwBoD0CAFicZ4HQHgEArEUAQEMEALAaWwBohwAA1nTrQiC0QQAAq3IhENog"
    "AIBVeRYIbRAAwOpsAWB7AgBYnS0AbE8AAJvY7cpdATYjAIDNeBYI2xEAwJY8C4SNCABgUy4EwjYEALApFwJhGwIA2JwtAKxPAACb"
    "swWA9QkAoAm2ALAuAQAr+fu/3v+q8KFhC+BZIKxHAMAKHP6jCQBYiQCAFfzwQ/lVYZTHh/19ARYnAGBhpv9pXAiEdQgAWNBw+Jv+"
    "p3MhEJYnAIDm2ALA8gQALMT0P48tACxLAMBCHP7zeBYIyxIAsAAX/6oRALAQAQALMP3XYwsAyxAAUJnpv7pbFwKhPgEAlZn+63Mh"
    "EOoTAFCR6X8ZngVCfQIAKvHsb1m2AFCXAAC6YAsAdQkAqMD0v47drtwVoAoBABU4/NfjWSDUIQBgJhf/VudZIFQgAGAm0//6XAiE"
    "+QQAzGD634YLgTCfAIAZTP/bsQWAeQQAXMn0vy1bAJhHAMAVPPtrgy0AXE8AAN0atgCeBcJ1BABMZPpvjgCAKwgAmMjh357Hh/19"
    "ASYRADCBi39tciEQphMAMIHpv10uBMI0AgBGMv23zRYAphEAMJLpv322ADCeAIARTP998CwQxhMA8AnP/rojAGAEAQCEYwsAnxMA"
    "cIHpv1u3LgTCZQIALnD498uFQLhMAMAHXPzrm2eBcJkAgA+Y/vtnCwAfEwBwhuk/BlsA+JgAgDNM/3HsduWuAO8IAHjD9B+PZ4Hw"
    "ngCAE579heVZILwhAIAUXAiE1wQAHJj+Y3MhEF4TAHDg8I/PFgB+JgCguPiXhS0A/EwAQDH9Z2ILAD8RAKRn+s9l2AJ4FggCAEz/"
    "OQkA0hMApGb6z+vxYX9fIDEBQFqe/eXmQiDZCQAgLRcCyUwAkJLpn4EtAJkJAFJy+HNkC0BWAoB0XPzjlGeBZCUASMf0zxkCgHQE"
    "AKmY/vmILQDZCABSMf1zwa0LgWQiAEjD9M9nXAgkEwFACp79MYZngWQiAABO2AKQhQAgPNM/U9gCkIUAIDyHP1PtduWuQHACgNBc"
    "/ONangUSnQAgNNM/M3gWSGgCgLBM/8zlQiCRCQDCMv0zlwuBRCYACMn0Ty22AEQlAAjHsz9qsgUgKgEA8AlbACISAIRi+mcJwxbA"
    "s0CiEQCE4vBnQQKAUAQAYbj4x9IeH/b3BYIQAIRh+mdpLgQSiQAgBNM/a3EhkCgEACGY/lmLLQBRCAC6Z/pnbbYARCAA6Jpnf2zB"
    "s0AiEAAA1xEAdE0A0C3TP1uzBaBnAoBuOfxpwK0LgfRKANAlF/9ohQuB9EoA0CXTP63wLJBeCQC6Y/qnNbYA9EgA0B3TP62xBaBH"
    "AoCumP5p1W5X7gp0RADQDc/+aJ1ngfREAADU41kg3RAAdMH0Ty9cCKQXAoAuOPzphQuB9EIA0DwX/+iNLQA9EAA0z/RPb2wB6IEA"
    "oGmmf3plC0DrBABNM/3Tq2EL4FkgLRMANMv0TwACgGYJAJrk2R9RPD7s7ws0SAAALMiFQFolAGiO6Z9oXAikRQKA5jj8icYWgBYJ"
    "AJri4h9R2QLQGgFAU0z/ROVZIK0RADTD9E8CAoBmCACaYfonA1sAWiEAaILpn0RuXQikBQKAzXn2RzYuBNICAQCwMs8CaYEAYFOm"
    "f7KyBWBrAoBNOfzJyhaArQkANuPiH9ntduWuwEYEAJsx/YNngWxHALAJ0z+88CyQTQgANmH6h5+5EMgWBACrM/3Day4EsgUBwKo8"
    "+4PzbAFYmwAAaIAtAGsTAKzG9A+X2QKwJgHAahz+cNmwBfAskLUIAFbh4h+MJgBYhQBgFaZ/GO/xYX9fYGECgMWZ/mEaFwJZgwBg"
    "caZ/mM6FQJYmAFiU6R+uYwvA0gQAi/HsD+axBWBJAgCgUZ4FsiQBwCJM/1CNAGARAoBFOPyhHlsAliAAqM7FP6ju1oVAahMAVGf6"
    "h/pcCKQ2AUBVpn9YhmeB1CYAqMr0D8uxBaAmAUA1pn9Yli0ANQkAqvDsD9ax25W7AhUIAIDOeBZIDQKA2Uz/sDrPAplNADCbwx/W"
    "50IgcwkAZnHxD7bhQiBzCQBmMf3DdmwBmEMAcDXTP2zLFoA5BABXM/3D9mwBuJYA4Cqmf2jDsAXwLJBrCAAm8+wPmiMAmEwAAATw"
    "+LC/LzCBAGAS0z+0yYVAphIATOLwh3a5EMgUAoDRXPyDttkCMIUAYDTTP7TPFoCxBACjmP6hD54FMpYAYBTTP3RFAPApAcCnTP/Q"
    "H1sAPiMAuMizP+jWrQuBXCIAAIJyIZBLBAAfMv1D3zwL5BIBwIcc/tA/WwA+IgA4y8U/iMEWgI8IAM4y/UMcu125K/CGAOAd0z/E"
    "41kgbwkA3jH9Q0ieBfKKAOAV0z/E5UIgpwQALzz7g9hcCOSUAABIxBaAIwHAM9M/5GALwJEA4JnDH/KwBWAgAHDxD5IZtgCeBSIA"
    "MP1DTgIgOQGQnOkf8np82N8X0hIAyZn+IS8XAnMTAImZ/gEXAvMSAEl59gcMbAHyEgAAydkC5CQAEjL9A6c8C8xJACTk8AfOEADJ"
    "CIBkXPwDPmILkIsASMb0D1xw60JgHgIgEdM/8BkXAvMQAImY/oHPeBaYhwBIwvQPjGULkIMASMCzP2AKW4AcBAAA7+x25a4QmgAI"
    "zvQPXMuzwNgEQHAOf2AGzwIDEwCBufgHzOVCYFwCIDDTPzCXC4FxCYCgTP9ALbYAMQmAoEz/QC22ADEJgIBM/0BttgDxCIBgPPsD"
    "ljBsATwLjEUAADCWAAhEAARi+geW9viwvy+EIAACcfgDS3MhMA4BEISLf8BaXAiMQQAEYfoH1mILEIMACMD0D6zNFqB/AiAA0z+w"
    "Ns8C+ycAOmf6BzYkADomADrm2R+wNVuAfgkAAOa4dSGwT18VumT6B7a235f/e/qv7779z5v/LXRHAHTK4Q9s7Lvf/cfNd4VuCYAO"
    "HaZ/gNWZ+uMQAB0y/QNrc/DHIwA6Y/oHNmDdH5AA6IzpH1iLqT82AdAR0z+wIlN/cAKgE579AWsYpv6ng/8PhfAEAADW/QkJgA6Y"
    "/oGFWfcnJAA64PAHlmDqz00ANM7FP6A2Bz8DAdA40z9QmXU/zwRAw0z/QC2mft4SAA0z/QOVmPp5RwA0yvQPzOVNP5cIgAZ59gfM"
    "Yd3PGAIAIBbrfkYRAI0x/QPXMPUzlQBojMMfmMLBz7UEQENc/AMmsu7nagKgIaZ/YAxTPzUIgEaY/oGRTP1UIQAaYfoHLvGmn9oE"
    "QCN++Kr8dyE0Cx6uYd3PUgRAI37/+5v/LwCvWfezGAEA0BhTP2sQAACNcPCzJgEA0AbrflYlAAA2ZOpnKwIAYDumfjYjAABW5k0/"
    "LRAAACux7qclAgBgHdb9NEUAACzI1E+rBADAAhz8tE4AANRn3U/zBABAJaZ+eiIAAOow9dMVAQAwgzf99EoAAFzBup/eCQCA6az7"
    "6Z4AABjJ1E8kAgDgEw5+IhIAAJdZ9xOSAAA4w9RPdAIA4D1TP+EJAIADb/rJRAAA6Vn3k5EAALKz7iclAQCkZOonOwEApOLgh58I"
    "ACAT6344EABAeKZ+eE8AANGZ+uEMAQCE5E0/XCYAgFCs+2EcAQBEYt0PIwkAoHumfphOAADdcvDD9QQA0CvrfphBAABdMfVDHQIA"
    "6ImpHyoRAEDzvOmH+gQA0CzrfliOAABaZd0PCxIAQFNM/bAOAQA0wcEP6xIAQAus+2FlAgDYjKkftiMAgK2Y+mFDAgBYlTf90AYB"
    "AKzCuh/aIgCANVj3Q2MEALAYUz+0SwAA1Tn4oX0CAKjNuh86IACAKkz90BcBANRg6ofOCADgat70Q78EADCZdT/0TwAAU1n3QwAC"
    "ABjF1A+xCADgIgc/xCQAgEus+yEoAQC8Y+qH+NIEwN/+1f7r4dcvX8r98OvNrnz/9j+zuyn/c/z9P/7zzfcFcjL1k9rxvDj6cV/+"
    "9PS/3/9Yvj6eIcO50et5cVOC++bP9795+r/y61LD/qc/8NN46PkPn1i++fX+l7tduStX8qaf6N4Ogi8qnBE3N+W/ejsPwgbA8Af9"
    "5cfym7KWN3EgDFjbtQFg3U807w76WkPgCEMI/O5f+gjpkAHw+Jf7+6e/0K6ehKp7igNhwNKuDIDv/unfrfvp05YH/UVPf+d/+283"
    "vy2NCxcAzR3+HzmJgl5qkbZNCQBTPz163uy2dth/pIMICHcJsIvDf/D0L+/TP+vzv8Df/MX++Z95WB0Nv9oSsBQHPz15e+A/fazb"
    "z9j69M87/PO3/Hd5qAB4vvDXsWO8fHn69SkKBAG1ud1P07o+8M843EP7u9KoMB8BrH7pbwuHjw0EAed89BGAqZ9WDX9vD0/shmd1"
    "za/0r9TypcAwG4C37zRDOnxs8HZD4A4BF5j6acrLlH+c8AeBH6Q/x02jfBNgx44fGTzfIbAd4IQ3/bTk3aEf/hto+hAmALq5/LcU"
    "2wGKdT9tePU8L/uh+65m4wAABThJREFU3/BHG2H+SJ4OvX8onGc7ACwsw+f51/rFrvy2xb974wRAza/8Dc52AKihq3f5G/r2X2+a"
    "fAngDkBCp3cHxAAwxel6/8tP0z6X7IvvAVjaL35R/hD+GeACxAAwxnHa/3K81e7gH+XcT55thQ0AL8QAcMrt/dhC/XF283MAOiMG"
    "II/TQ78wS+s/GTBcz7kMuCwxAPG4zLeMVi//HYX7CMBdgGX5mADiePW5vvV+Vce/H1sW8o/cRwHrEwPQByv+5bW++j8K3XxCYBvD"
    "v/y+dAja4dBfyb58P2yhe/m7L/zSZ4iA4VffTrUNMQDbcfCv4PDOv6eD/yjdpz7HL7EYnPsJgq9+cpP/p6mql7UY9MyhP9OZL+45"
    "fcs/DDTH3/c+2Lj2McHxu66H39sozHD42QRiAOpwi3+CwwF//Pkow++zbigFQAWnYTAQBxOIAbiaaf8CB/2nBMCCbAym8ZIAPufQ"
    "P+Pkc/jhVwf9OAJgZa+iwAuFD4kB+JkftftGxxfvWiIANiYIPicGyMq0f+DAX4QAaNDL00VB8I4YIDqHfnHgr0QAdEAQnCcGiMKK"
    "v7x8ic7wW4f+OgRAZ8TAeWKAHqWf9h36mxIAHTM1nCcGaJlDv6+vy41MAARiO/CeGKAFDn2HfosEQFAv2wEx8EIMsKb0387n0G+e"
    "AEhADLwnBljC8WeNpJ32HfpdEQDJuDfwnhhgDoe+Q79XAiC54d6AGDhx+NkEfoQxlzj03d6PQADwQgy8ZzvAkc/0fTlPNAKAs8TA"
    "e2IgHz9mt1jxByYA+JQYOOPwUcHwW0EQi0O/OPSTEACM5jXBBe4OdMvF2AP/DqcjALiKGPiEv0yblf4C31um/bQEALP5BsLPHe8P"
    "CIJtWOu/4dCnCAAqEwMjuUOwKGv9M9zi5w0BwGLEwDS2BNd5tdIfOPBfM+3zAQHAKsTAdUTBaw77kRz6jCAAWJ0YmOnk44MhDIZf"
    "o/1FfzzoX9b4A4f95xz8TCAA2JTvGKjsJA4GLW8OHPKVOPS5kgCgGWJgYYdLYKeBcOq4TTj12aFyPMTfGg71V/+rfzz5M/XnO59D"
    "nwoEAE16jgEfEcBrDn4qEgA0zRcOkZ5Dn4UIALohBkjDoc8KBABdEgOEczj0h986+FmDAKB7YoCumfbZiAAgFF8BSxcc+jRAABCa"
    "p4U0w6FPYwQAafgGQlbn0KdhAoCUxACLcejTCQFAeu4NMJtDnw4JAHjDdoBRHPp0TgDABS8xYDvA4Qct+dHMRCEAYALbgUQOPzzJ"
    "lE9UAgBmEATB+DY+EhEAUJEg6Iwpn8QEACzk+Lpg+L0gaMTJgT/86tAnMwEAKxIFK3NxDz4kAGBjoqCSk8N++G8d+HCZAIAGiYJP"
    "WOXDbAIAOjFEwfDrSxj8ePhegqjfT3A45E+n+oHDHuoQABDE6dZg0MWXF5055B3wsA4BAAkctwdHp6Fw6mWrcOqjiDgc3u/+47vX"
    "//PT6f3IIQ/bEwAAkNBXBQBIRwAAQEICAAASEgAAkJAAAICEBAAAJCQAACAhAQAACQkAAEhIAABAQgIAABISAACQkAAAgIQEAAAk"
    "JAAAICEBAAAJCQAASEgAAEBCAgAAEhIAAJCQAACAhAQAACQkAAAgIQEAAAkJAABISAAAQEICAAASEgAAkJAAAICEBAAAJCQAACAh"
    "AQAACQkAAEhIAABAQgIAABISAACQkAAAgIQEAAAkJAAAICEBAAAJCQAASEgAAEBCAgAAEhIAAJCQAACAhAQAACQkAAAgIQEAAAkJ"
    "AABI6I8AAAD//04wo/sAAAAGSURBVAMAVdzMXby37aEAAAAASUVORK5CYII="
)
